'use client'

import React, { useState } from "react";
import CardPic from "@/components/ui/cardPic";
import {Tabs, Tab, Card, CardBody} from "@nextui-org/react";

export default function Showcase() {

  return (
    <section className="flex gap-4 flex-col">
      <div>
        <h1 className="font-extrabold text-[32px]">Showcase</h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by WFT</p>
      </div>
    <div className="flex w-full flex-col">
      
      <Tabs aria-label="Options">
        <Tab key="photos" title="All">
          <CardPic/>          
        </Tab>
        <Tab key="music" title="Anime">
          <CardPic/>
        </Tab>
        <Tab key="videos" title="Stable Diffusion">
          <CardPic/>
        </Tab>
      </Tabs>
    </div>
    </section>
  );
}
