'use client'

import React from "react";
import TabContents from "@/components/TabContents"


export default function Showcase() {

  return (
    <div className="flex gap-4 flex-col">
      <div>
        <h1 className="font-extrabold text-[32px]">Showcase</h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by WFT</p>
      </div>

      <div className="flex w-full flex-col">      
        <TabContents />
      </div>
    </div>
  );
}
